import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Quick Start',
      items: ['quick-start/install'],
    },
    {
      type: 'category',
      label: 'What\'s Installed',
      items: [
        'whats-installed/shell-setup',
        'whats-installed/command-line-tools',
        'whats-installed/languages',
        'whats-installed/applications',
        'whats-installed/optional-ides',
        'whats-installed/system-tweaks',
      ],
    },
    {
      type: 'category',
      label: 'Post-Installation',
      items: [
        'post-installation/github-ssh',
        'post-installation/badal-specifics',
        'post-installation/tips',
      ],
    },
    {
        type: 'category',
        label: 'Script Deep Dive',
        items: [
            'script-deep-dive/setup-new-computer',
            'script-deep-dive/functions',
            'script-deep-dive/badal-io',
        ],
    },
    {
        type: 'category',
        label: 'For Other Companies',
        items: ['for-other-companies/forking'],
    },
    {
        type: 'category',
        label: 'Contributing',
        items: ['contributing/development'],
    }
  ],
};

export default sidebars;
